/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  developersSidebar: [
    "developers/getting-started/index",
    {
      type: "category",
      label: "Getting started",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Testnet Tokens",
          id: "developers/getting-started/acquire-testnet-tokens",
        },
        {
          type: "doc",
          label: "UniFi Native Bridge",
          id: "developers/getting-started/bridge-ui",
        },
      ]
    },
    {
      type: "category",
      label: "Deploy a Smart Contract",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Using Foundry",
          id: "developers/rollup/smart-contracts/deploy-foundry",
        },
        {
          type: "doc",
          label: "Using Hardhat",
          id: "developers/rollup/smart-contracts/deploy-hardhat",
        }
      ]
    },
    {
      type: "category",
      label: "Concepts",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        {
          type: "doc", 
          label: "Architecture",
          id: "developers/concepts/architecture",
        },
        {
          type: "doc", 
          label: "Gateway",
          id: "developers/concepts/gateway",
        },
        {
          type: "doc", 
          label: "TEE Multi Prover",
          id: "developers/concepts/tee-multi-prover",
        },
        {
          type: "doc", 
          label: "Signal Service",
          id: "developers/concepts/signal-service",
        },
      ]
    },
    {
      type: "category",
      label: "Reference",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Network & RPC Endpoints",
          id: "developers/reference/rpc-endpoints",
        },
        {
          type: "doc",
          label: "Custom Wallet Setup for Pre-confirmations",
          id: "developers/reference/custom-preconfirmation-wallet-setup",
        },
        {
          type: "doc",
          label: "Smart Contract Addresses",
          id: "developers/reference/contract-addresses",
        },
        {
          type: "doc",
          label: "Opcodes",
          id: "developers/reference/opcodes",
        },
        {
          type: "doc",
          label: "L1 to L2 Composability Examples",
          id: "developers/reference/L1-to-L2-composability-examples",
        },
      ]
    }
  ]
};

module.exports = sidebars;